# docking_viz.py
# ============================================================
# SALIDOCK — Publication-Quality Visualization Orchestrator
# PyMOL open-source | PLIP | APBS | PDB2PQR
# ============================================================

import os
import sys

# Ensure the directory of the current Python executable is prepended to PATH
# so that conda environment binaries (pymol, plip, apbs, pdb2pqr) are always discoverable.
python_bin_dir = os.path.dirname(sys.executable)
if python_bin_dir and python_bin_dir not in os.environ.get("PATH", ""):
    os.environ["PATH"] = python_bin_dir + os.pathsep + os.environ.get("PATH", "")

import shutil
import subprocess
import logging
from pathlib import Path
import xml.etree.ElementTree as ET
from typing import List, Dict, Optional, Tuple

logger = logging.getLogger(__name__)

def create_complex_pdb(
    protein_pdbqt: Path,
    ligand_pdbqt: Path,
    output_pdb: Path,
    pose_number: int = 1
) -> bool:
    """
    Merge receptor and ligand pose into a single PDB file.
    Forces the ligand residue name to 'LIG' and record type to 'HETATM' for visualizer consistency.
    """
    try:
        if not protein_pdbqt.exists():
            logger.error(f"Protein file not found: {protein_pdbqt}")
            return False
        if not ligand_pdbqt.exists():
            logger.error(f"Ligand file not found: {ligand_pdbqt}")
            return False

        pdb_lines = []
        pdb_lines.append("REMARK   Protein-Ligand Complex generated by SALIDOCK")
        pdb_lines.append(f"REMARK   Protein source: {protein_pdbqt.name}")
        pdb_lines.append(f"REMARK   Ligand source: {ligand_pdbqt.name} (Pose {pose_number})")

        # Read protein atoms (prefer prepared PDB if it exists to preserve residue numbering)
        protein_pdb_path = protein_pdbqt.parent / "protein_prepared.pdb"
        protein_source = protein_pdb_path if protein_pdb_path.exists() else protein_pdbqt
        
        protein_content = protein_source.read_text()
        protein_atoms = 0
        for line in protein_content.splitlines():
            if line.startswith(('ATOM', 'HETATM')):
                pdb_lines.append(line[:66].rstrip())
                protein_atoms += 1
            elif line.startswith('REMARK'):
                pdb_lines.append(line)

        # Add TER separator
        pdb_lines.append("TER")

        # Extract specific ligand pose from docking output
        from results import extract_pose_from_pdbqt
        ligand_pose = extract_pose_from_pdbqt(str(ligand_pdbqt), pose_number)
        
        ligand_atoms = 0
        for line in ligand_pose.splitlines():
            if line.startswith(('ATOM', 'HETATM')):
                pdb_line = line[:66].rstrip()
                if pdb_line.startswith('ATOM'):
                    pdb_line = 'HETATM' + pdb_line[6:]
                
                # Standardize ligand residue name to 'LIG' (columns 18-20, index 17:20)
                if len(pdb_line) < 20:
                    pdb_line = pdb_line.ljust(20)
                pdb_line = pdb_line[:17] + 'LIG' + pdb_line[20:]
                
                pdb_lines.append(pdb_line)
                ligand_atoms += 1

        pdb_lines.append("END")
        
        output_pdb.write_text('\n'.join(pdb_lines))
        logger.info(f"Successfully generated merged PDB with {protein_atoms} protein atoms and {ligand_atoms} ligand atoms at {output_pdb}")
        return True
    except Exception as e:
        logger.error(f"Error creating complex PDB: {e}", exc_info=True)
        return False

def parse_plip_residues(xml_path: Path) -> List[Dict]:
    """
    Parse PLIP report.xml to extract unique interacting residue identifiers.
    Returns: [{'resnr': 72, 'restype': 'ASP', 'reschain': 'A'}, ...]
    """
    residues = []
    seen = set()
    if not xml_path.exists():
        logger.warning(f"PLIP report.xml not found at {xml_path}")
        return residues
    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
        
        # Build parent map to navigate siblings in element tree
        parent_map = {c: p for p in root.iter() for c in p}
        
        for resnr_elem in root.iter('resnr'):
            resnr = resnr_elem.text
            if not resnr:
                continue
            parent = parent_map.get(resnr_elem)
            if parent is not None:
                restype_elem = parent.find('restype')
                reschain_elem = parent.find('reschain')
                
                restype = restype_elem.text if restype_elem is not None else ""
                reschain = reschain_elem.text if reschain_elem is not None else "A"
                
                key = (restype, resnr, reschain)
                if key not in seen:
                    seen.add(key)
                    residues.append({
                        'resnr': int(resnr),
                        'restype': restype,
                        'reschain': reschain
                    })
    except Exception as e:
        logger.error(f"Error parsing PLIP report.xml: {e}", exc_info=True)
    return residues

def run_plip_analysis(complex_pdb: Path, output_dir: Path) -> Optional[Path]:
    """
    Run PLIP command-line tool on the complex PDB file.
    """
    try:
        output_dir.mkdir(exist_ok=True, parents=True)
        
        # Check PLIP availability
        plip_bin = shutil.which("plip")
        if not plip_bin:
            logger.error("PLIP executable not found in path.")
            return None

        cmd = [
            plip_bin,
            "-f", str(complex_pdb),
            "-o", str(output_dir),
            "--pymol",
            "--nohydro",
            "-x",  # Generate XML output
        ]
        
        logger.info(f"Running PLIP command: {' '.join(cmd)}")
        res = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        
        if res.returncode != 0:
            logger.error(f"PLIP command failed: stdout={res.stdout}, stderr={res.stderr}")
            return None
            
        pse_files = list(output_dir.glob("*.pse"))
        if not pse_files:
            logger.error("PLIP ran successfully but did not produce a .pse session file.")
            return None
            
        return pse_files[0]
    except Exception as e:
        logger.error(f"Failed to run PLIP analysis: {e}", exc_info=True)
        return None

def run_apbs_electrostatics(complex_pdb: Path, session_dir: Path) -> Optional[Path]:
    """
    Run pdb2pqr and apbs to generate an electrostatic potential map (.dx file).
    """
    try:
        pqr_path = session_dir / "complex.pqr"
        apbs_in_path = session_dir / "apbs.in"
        
        # Locate executables
        pdb2pqr_bin = shutil.which("pdb2pqr")
        apbs_bin = shutil.which("apbs")
        
        if not pdb2pqr_bin or not apbs_bin:
            logger.warning(f"APBS/PDB2PQR executables not fully found: pdb2pqr={pdb2pqr_bin}, apbs={apbs_bin}. Skipping electrostatics.")
            return None
            
        # 1. Run pdb2pqr
        pdb2pqr_cmd = [
            pdb2pqr_bin,
            "--ff=AMBER",
            f"--apbs-input={str(apbs_in_path)}",
            str(complex_pdb),
            str(pqr_path)
        ]
        logger.info(f"Running PDB2PQR: {' '.join(pdb2pqr_cmd)}")
        res_pqr = subprocess.run(pdb2pqr_cmd, capture_output=True, text=True, timeout=90)
        if res_pqr.returncode != 0:
            logger.error(f"PDB2PQR failed: stdout={res_pqr.stdout}, stderr={res_pqr.stderr}")
            return None
            
        if not apbs_in_path.exists():
            logger.error("PDB2PQR ran but apbs.in template was not created.")
            return None
            
        # 2. Run APBS
        apbs_cmd = [apbs_bin, str(apbs_in_path)]
        logger.info(f"Running APBS: {' '.join(apbs_cmd)}")
        res_apbs = subprocess.run(apbs_cmd, capture_output=True, text=True, cwd=str(session_dir), timeout=120)
        if res_apbs.returncode != 0:
            logger.error(f"APBS failed: stdout={res_apbs.stdout}, stderr={res_apbs.stderr}")
            return None
            
        # Find generated dx grid files
        dx_files = list(session_dir.glob("*.dx"))
        if dx_files:
            logger.info(f"APBS generated electrostatic grid map: {dx_files[0].name}")
            return dx_files[0]
            
        logger.error("APBS completed but no .dx grid file was generated.")
        return None
    except Exception as e:
        logger.error(f"Failed to generate APBS electrostatics: {e}", exc_info=True)
        return None

def write_pymol_script(
    pse_path: Path,
    apbs_dx_path: Optional[Path],
    output_pml: Path,
    key_residues: List[Dict],
    light_png: Path,
    dark_png: Path,
    electrostatic_png: Optional[Path]
):
    """
    Generate customized PML script containing PyMOL styling, selections, labeling, and rendering commands.
    """
    lines = []
    lines.append("# SALIDOCK visualization script")
    lines.append(f"load {pse_path.as_posix()}")
    
    # Global visual settings
    lines.append("set antialias, 2")
    lines.append("set hash_max, 300")
    lines.append("set ray_shadows, 1")
    lines.append("set depth_cue, 1")
    lines.append("set fog_start, 0.45")
    
    # Color definitions and standard element representation
    lines.append("select ligand, resn LIG")
    lines.append("select binding_site, byres (ligand around 5.0)")
    
    # Hide default protein lines and render as modern cartoon
    lines.append("hide everything, polymer")
    lines.append("show cartoon, polymer")
    lines.append("color marine, polymer")
    lines.append("set cartoon_transparency, 0.15")
    lines.append("set cartoon_fancy_helices, 1")
    
    # Style binding site residues
    lines.append("show sticks, binding_site")
    lines.append("util.cnc binding_site")
    lines.append("set stick_radius, 0.12, binding_site")
    
    # Style ligand representation
    lines.append("show sticks, ligand")
    lines.append("show spheres, ligand")
    lines.append("color yellow, ligand")
    lines.append("set sphere_scale, 0.18, ligand")
    lines.append("set stick_radius, 0.20, ligand")
    
    # Label key interacting residues if parsed
    if key_residues:
        resi_list = "+".join(str(r['resnr']) for r in key_residues)
        lines.append(f"select key_residues, (resi {resi_list} and polymer)")
        lines.append('label key_residues and name CA, "%s%s" % (resn, resi)')
        lines.append("set label_size, 12")
        lines.append("set label_font_id, 7")
        lines.append("set label_shadow_mode, 2")
        lines.append("set label_bg_color, white")
        lines.append("set label_bg_transparency, 0.4")
        
    # Standard transparent pocket surface
    lines.append("create pocket_surface, binding_site")
    lines.append("show surface, pocket_surface")
    lines.append("color lightblue, pocket_surface")
    lines.append("set transparency, 0.65, pocket_surface")
    
    # Orient camera
    lines.append("orient ligand")
    lines.append("zoom ligand, 8")
    
    # --- RENDER 1: White Background / Light Theme ---
    lines.append("bg_color white")
    lines.append("set ray_opaque_background, on")
    if key_residues:
        lines.append("set label_color, black")
    lines.append("set ray_trace_mode, 1")
    lines.append("ray 1600, 1200")
    lines.append(f"png {light_png.as_posix()}, dpi=300, ray=1")
    
    # --- RENDER 2: Black Background / Dark Theme ---
    lines.append("bg_color black")
    if key_residues:
        lines.append("set label_color, white")
    lines.append("ray 1600, 1200")
    lines.append(f"png {dark_png.as_posix()}, dpi=300, ray=1")

    # --- RENDER 3: Electrostatics (APBS) if dx file exists ---
    if apbs_dx_path and electrostatic_png:
        lines.append(f"load {apbs_dx_path.as_posix()}, elec_map")
        lines.append("ramp_new elec_ramp, elec_map, [-5, 0, 5], [red, white, blue]")
        lines.append("set surface_color, elec_ramp, pocket_surface")
        lines.append("set transparency, 0.45, pocket_surface")
        lines.append("bg_color white")
        lines.append("set ray_opaque_background, on")
        if key_residues:
            lines.append("set label_color, black")
        lines.append("ray 1600, 1200")
        lines.append(f"png {electrostatic_png.as_posix()}, dpi=300, ray=1")
        
    output_pml.write_text('\n'.join(lines))
    logger.info(f"Custom PML script written to {output_pml}")

def generate_pose_visualizations(
    session_id: str,
    pose_number: int,
    protein_pdbqt: Path,
    ligand_pdbqt: Path,
    results_dir: Path
) -> Dict[str, str]:
    """
    Main entry orchestrator for creating premium visual assets for a docking pose.
    Creates:
    - Merged complex PDB
    - PLIP session PSE file
    - APBS dx surface mapping grid
    - White background, black background, and electrostatic surface ray-traced figures
    - SVG 2D interaction diagram (via RDKit fallback or ProLIF)
    """
    assets = {}
    session_dir = protein_pdbqt.parent
    
    # 1. Paths configurations
    complex_pdb = session_dir / f"complex_pose_{pose_number}.pdb"
    plip_out_dir = session_dir / f"plip_pose_{pose_number}"
    pml_path = session_dir / f"render_pose_{pose_number}.pml"
    
    light_png = results_dir / f"pose_{pose_number}_light.png"
    dark_png = results_dir / f"pose_{pose_number}_dark.png"
    electro_png = results_dir / f"pose_{pose_number}_electrostatic.png"
    
    # 2. Merge complex PDB
    if not create_complex_pdb(protein_pdbqt, ligand_pdbqt, complex_pdb, pose_number):
        logger.error("Visualization pipeline aborted: Complex PDB creation failed.")
        return assets
    
    # Save complex PDB path to assets
    assets['complex_pdb'] = str(complex_pdb.name)
    
    # 3. Run PLIP Analysis
    pse_path = run_plip_analysis(complex_pdb, plip_out_dir)
    if not pse_path:
        logger.error("Visualization pipeline: PLIP run failed.")
        return assets
        
    # Copy plip pse to standard name
    pse_target = results_dir / f"pose_{pose_number}_session.pse"
    shutil.copy(pse_path, pse_target)
    assets['pymol_session'] = f"pose_{pose_number}_session.pse"
    
    # Parse residues from report.xml
    report_xml = plip_out_dir / "report.xml"
    key_residues = parse_plip_residues(report_xml)
    logger.info(f"Interactions parsed: found {len(key_residues)} unique interacting residues.")
    
    # 4. Generate APBS electrostatics
    apbs_dx = run_apbs_electrostatics(complex_pdb, session_dir)
    
    # 5. Render PyMOL ray-traced figures
    pymol_bin = shutil.which("pymol")
    if pymol_bin:
        write_pymol_script(
            pse_path=pse_target,
            apbs_dx_path=apbs_dx,
            output_pml=pml_path,
            key_residues=key_residues,
            light_png=light_png,
            dark_png=dark_png,
            electrostatic_png=electro_png if apbs_dx else None
        )
        
        # Execute PyMOL headless
        pymol_cmd = [pymol_bin, "-cq", str(pml_path)]
        logger.info(f"Running headless PyMOL: {' '.join(pymol_cmd)}")
        res_pymol = subprocess.run(pymol_cmd, capture_output=True, text=True, timeout=120)
        
        if res_pymol.returncode == 0:
            if light_png.exists():
                assets['render_light'] = light_png.name
            if dark_png.exists():
                assets['render_dark'] = dark_png.name
            if apbs_dx and electro_png.exists():
                assets['render_electrostatic'] = electro_png.name
            logger.info("Successfully generated ray-traced PyMOL figures.")
        else:
            logger.error(f"PyMOL render command failed: {res_pymol.stderr}")
    else:
        logger.error("PyMOL executable not found. Unable to render premium ray-traced figures.")

    # 6. Generate 2D Interaction Diagram (using native PLIP SVG if available)
    try:
        svg_files = list(plip_out_dir.glob("*.svg"))
        if svg_files:
            svg_target = results_dir / f"pose_{pose_number}_2d.svg"
            shutil.copy(svg_files[0], svg_target)
            assets['diagram_2d'] = svg_target.name
            logger.info(f"Successfully copied native PLIP 2D interaction diagram to {svg_target}")
        else:
            logger.warning("PLIP native SVG not found. Falling back to custom interaction_2d logic.")
            import interaction_2d
            # If ligand_ref.sdf is available, use it for kekulized template bond order assignment
            ligand_ref = session_dir / "ligand_ref.sdf"
            ref_path = str(ligand_ref) if ligand_ref.exists() else None
            
            # Vina results affinity
            from results import parse_vina_output
            affinity = 0.0
            try:
                vina_res = parse_vina_output(str(ligand_pdbqt))
                if len(vina_res) >= pose_number:
                    affinity = vina_res[pose_number - 1].get('affinity', 0.0)
            except Exception:
                pass
                
            # Detect interactions via internal interaction_2d engine
            prot_atoms, lig_atoms = interaction_2d.parse_pdb(str(complex_pdb))
            detected_acts = interaction_2d.detect(prot_atoms, lig_atoms)
            
            # Generate SVG
            svg_content = interaction_2d.render_svg(
                pdb_path=str(complex_pdb),
                interactions=detected_acts,
                affinity=affinity,
                original_sdf_path=ref_path
            )
            
            svg_out = results_dir / f"pose_{pose_number}_2d.svg"
            svg_out.write_text(svg_content, encoding="utf-8")
            assets['diagram_2d'] = svg_out.name
            logger.info(f"Successfully generated custom 2D interaction diagram at {svg_out}")
    except Exception as e:
        logger.error(f"Failed to generate 2D interaction diagram: {e}", exc_info=True)

    return assets
